name: Print Environment Variables

on:
  pull_request:
    branches:
      - main

jobs:
  print-messages:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "Hello Bootcamp from the environment variable!!!"
    steps:
      - name: Print environment variable
        run: echo "The environment variable is: ${{ env.MY_ENV_VAR }}"

      - name: Print secret
        run: echo "The secret is: ${{ secrets.MY_SECRET }}"